random_words = [
    "apple", "banana", "cat", "dog", "egg", "fish", "grape", "hat", "ice", "jam",
    "kite", "lemon", "moon", "nose", "orange", "pencil", "queen", "rain", "sun", "tree",
    "umbrella", "violin", "water", "xray", "yellow", "zebra", "ant", "ball", "car", "desk",
    "elephant", "flower", "goat", "house", "island", "jump", "key", "lamp", "mouse", "net",
    "ocean", "pizza", "quilt", "rabbit", "snake", "turtle", "under", "van", "window", "xylophone",
    "yogurt", "zoo", "air", "book", "chair", "door", "ear", "fork", "garden", "heart",
    "iceberg", "jungle", "kettle", "lion", "milk", "nut", "open", "pillow", "quiet", "river",
    "stone", "table", "uncle", "vase", "whale", "xenon", "yawn", "zippy", "angel", "beach",
    "candy", "duck", "earth", "family", "gold", "honey", "idea", "joke", "kind", "leaves",
    "music", "night", "octopus", "party", "quick", "rainbow", "smile", "train", "understand", "vivid",
    "wonder", "xray", "yummy", "zesty", "big", "clap", "drum", "eat", "fast",
    "grin", "happy", "igloo", "jolly", "kitten", "love", "mango", "nap", "owl", "play",
    "quietly", "run", "sing", "top", "up", "visit", "whisper", "excite", "yarn", "zoom",
    "able", "baby", "cool", "dream", "easy", "fun", "gift", "hope", "inspire", "jumping",
    "kindness", "lucky", "magic", "nice", "peace", "quickly", "rest", "sunshine", "thankful",
    "unique", "victory", "warm", "excellent", "young", "zipper", "apron", "butter", "cup", "dance",
    "echo", "famous", "good", "harmony", "jewel", "light", "mirror", "nest",
    "opera", "puppy", "rose", "splash", "tender", "violet", "wave", "exciting",
    "zigzag", "amazing", "bright", "cloud", "delight", "enjoy", "friend", "giggle", "hug",
    "interesting", "joy", "laughter", "moment", "open", "pure", "quiet", "restful", "silly",
    "thrill", "victory", "wild", "exotic", "youth", "zen", "aroma", "bouncy", "cocoa", "doodle",
    "emerald", "frost", "glow", "mystic", "oasis", "peaceful", "refresh", "serene", "thrilling",
    "unicorn", "warm", "zebra", "arcade", "ballad", "crescent", "duet", "epic", "finesse",
    "groove", "hymn", "jazzy", "lyric", "melody", "noodle", "panorama", "quintet",
    "rhapsody", "sonnet", "tempo", "undertone", "whirl", "yodel", "zenith",
    "amaranth", "bliss", "celestial", "dewdrop", "ethereal", "fawn", "halcyon", "iridescent",
    "jubilant", "kindred", "luminescence", "mystic", "nirvana", "panache", "quintessence",
    "resplendent", "serenity", "tranquil", "umbra", "vernal", "whimsical", "xenon", "zephyr",
    "astral", "bewilder", "delirium", "eldritch", "fascination", "hazy", "illusory", "jittery",
    "lurid", "mystique", "nebulous", "phantom", "quirky", "reclusive", "spectral", "tenebrous",
    "uncanny", "vexing", "weird", "xenomorph", "yearning", "zealous", "alluring", "captivating",
    "dreamy", "fabled", "glistening", "imagine", "jeweled", "lively", "moonbeam", "nymph",
    "radiant", "soulful", "timeless", "unearthly", "wistful", "yearlong", "zesty",
    "bizarre", "charismatic", "dizzying", "enchanting", "glowing", "hushed", "joyous",
    "kismet", "legendary", "mesmerizing", "ominous", "peculiar", "resilient", "sublime",
    "thunderous", "unwavering", "vibrant", "wondrous", "zenith", "adorable", "brilliant",
    "cheerful", "dazzling", "exuberant", "fun-loving", "grateful", "hopeful", "intense",
    "jolly", "kindhearted", "majestic", "outstanding", "playful", "quick", "rejuvenated",
    "spirited", "trusting", "uplifted", "valiant", "wise", "exuberance", "youthful", "zany",
    "artistic", "breezy", "carefree", "delicate", "eager", "fearless", "genuine", "huggable",
    "ideal", "joyful", "keen", "limitless", "miraculous", "open", "perfect", "radiant",
    "satisfied", "tender", "universal", "vibrant", "warmhearted", "extraordinary",
    "yummy", "admirable", "brilliant", "delighted", "effortless", "festive", "genuine",
    "helpful", "innovative", "joyful", "kindness", "luminous", "magnificent", "noble",
    "outstanding", "playful", "radiant", "sublime", "thrilling", "unforgettable",
    "victorious", "whimsical", "zesty"
]

random_symbols = [
    "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "-", "_", "=", "+", 
    "[", "]", "{", "}", "|", "\\", ":", ";", "'", "\"", "<", ">", ",", ".", 
    "?", "/", "~", "`"
]